version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-sam-golang-example"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bw5aglvcdru5"
s3_prefix = "aws-sam-golang-example"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
