AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: An example serverless API and worker written in Golang.

Resources:
  Api:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: api
      Timeout: 30
      Events:
        RootHandler:
          Type: Api
          Properties:
            Method: any
            Path: /
        EverythingElse:
          Type: Api
          Properties:
            Method: any
            Path: /{proxy+}

Outputs:
  Endpoint:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
